//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement.Client.DB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student : Person
    {
        public Student()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public string IBAN { get; private set; }
        public string BIC { get; private set; }
        public string Depositor { get; private set; }
        public string NameOfBank { get; private set; }
    
        public virtual ICollection<Payment> Payment { get; private set; }
    }
}
