//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTool.Client.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Forename { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Address { get; set; }
        public string MobilePhone { get; set; }
        public string Mail { get; set; }
        public string Fax { get; set; }
        public string PrivatePhone { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Title { get; set; }
    }
}
