//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement.Client.DB.Model_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Tutors = new HashSet<Tutor>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int CourseNr { get; private set; }
        public string Title { get; private set; }
        public Nullable<decimal> AmountInEuro { get; private set; }
        public string Description { get; private set; }
        public Nullable<System.DateTime> StartDate { get; private set; }
        public Nullable<System.DateTime> EndDate { get; private set; }
        public Nullable<decimal> MaxMember { get; private set; }
        public Nullable<decimal> MinMember { get; private set; }
        public Nullable<decimal> ValidityInMonth { get; private set; }
    
        public virtual ICollection<Tutor> Tutors { get; private set; }
        public virtual ICollection<Payment> Payment { get; private set; }
        public virtual Room Rooms { get; private set; }
    }
}
