//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement.Client.DB.Model_EF
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Person
    {
        public int Id { get; protected set; }
        public string Surname { get; protected set; }
        public string Forename { get; protected set; }
        public Nullable<System.DateTime> Birthdate { get; protected set; }
        public string Street { get; protected set; }
        public string MobilePhone { get; protected set; }
        public string Mail { get; protected set; }
        public string Fax { get; protected set; }
        public string PrivatePhone { get; protected set; }
        public Nullable<byte> Gender { get; protected set; }
        public Nullable<bool> Active { get; protected set; }
        public string Title { get; protected set; }
        public string City { get; protected set; }
        public string CityCode { get; protected set; }
    }
}
